export default Object.freeze({
    LandingPage: "/",
    FinhackPage: "/finhack",
    ProductsPage: "/products",
    CompanyPage: "/company",
    ContactPage: "/contact-us",
    LoginPage: "/login-register",
    PasswordRecovery: "/password-recovery",
    PasswordReset: "/reset-password",
    SearchPage: "/search-result",
    LoanRequestPage: "/loan-request",
    DashboardPage: "/dashboard",
    LoansPage: "/loans",
    ProfilePage: "/profile",
    SettingsPage: "/settings",
});